[[target]]
name   = "gverb"
description = "Run simulations with ghdl and verb"
command = "python"
args    = ["gverb.py"]
fileset.pymdl = "{{orbit.tb.name}}.py"

[[target]]
name = "vverb"
description = "Run simulationrs with verilator and verb"
command = "python"
args = ["vverb.py"]
fileset.pymdl = "{{orbit.tb.name}}.py"
