[[target]]
name   = "gverb"
description = "Run simulations with ghdl and verb"
command = "python"
args    = ["gverb.py"]
fileset.pymdl = "{{orbit.tb.name}}.py"

[[target]]
name = "vsim"
description = "Run simulations using verilator"
command = "python"
args = ["vsim.py"]
fileset.pymdl = "{{orbit.tb.name}}.py"
