[[target]]
name   = "gverb"
description = "Run simulations with ghdl and verb"
command = "python"
args    = ["gverb.py"]
fileset.pymdl = "{{ orbit.bench }}.py"
explanation = """
Analyzes and simulates a testbench with GHDL. This target supports running
a design model in Python to generate test vectors using the Verb simulation
framework.

Help:
    orbit build --target gverb --force -- --help

Environment:
    ORBIT_ENV_GHDL_PATH             Filesystem path specifying GHDL binary

Dependencies:
    GHDL (tested: 3.0.0-dev (2.0.0.r101.g791ff0c1) [Dunoon edition])
    Python (tested: 3.8.6)
"""

[test]
default-target = "gverb"