[package]
name = "vertex"
version = "0.1.0"
edition = "2021"
description = "A tool for functional verification"

[dependencies]
cliproc = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0"