name: Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: cdotrus/verb/.github/workflows/build.yml@trunk
  test:
    uses: cdotrus/verb/.github/workflows/test.yml@trunk