name: test
on:
  workflow_call:

env:
  project: vertex

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Setup orbit
        uses: cdotrus/setup-orbit@v0

      - name: Setup ghdl
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Configure Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Enable Cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Test software library
        run: python -m unittest src/lib/python/tests/*.py

      - name: Test hardware library
        run: |
          just agglo-vhdl
          cp -R .orbit ./src/lib/vhdl
          cd ./src/lib/vhdl
          orbit plan --clean --top basic --plugin gvert
          orbit build

      - name: Test command-line application
        run: cargo test --verbose
