name: test
on:
  workflow_call:

env:
  project: vertex

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Setup orbit
        uses: cdotrus/setup-orbit@v0

      - name: Setup ghdl
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: mcode

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Configure Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Enable Cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Configure orbit plugins
        run: orbit config --append include=$PWD"/.orbit/config.toml"

      - name: Install Vertex components
        run: just dev-install

      - name: Test software library
        run: python -m unittest src/lib/python/tests/*.py

      - name: Test hardware library
        working-directory: ./src/lib/vhdl
        run: |
          orbit plan --clean --top basic --plugin gvert
          orbit build

      - name: Test command-line application
        working-directory: ./src/bin/vertex
        run: cargo test --verbose
