name: Test
on:
  workflow_call:

env:
  project: verb

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Setup orbit
        uses: cdotrus/setup-orbit@v0

      - name: Setup ghdl
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: mcode

      - name: Configure Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Enable Cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Install verb components
        run: just dev-install

      - name: Test software library
        run: python -m unittest src/lib/python/tests/*.py

      - name: Test hardware library
        working-directory: ./src/lib/vhdl
        run: orbit test

      - name: Test command-line application
        working-directory: ./src/bin/verb
        run: cargo test --verbose
